CREATE DATABASE PROJECT
    CHARACTER SET utf8
    COLLATE utf8_general_ci;

CREATE TABLE MARK(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE BODY(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE PICTURE(
    id INT NOT NULL AUTO_INCREMENT,
    path VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE CAR(
    id INT NOT NULL AUTO_INCREMENT,
    markId INT NOT NULL,
    bodyId INT NOT NULL,
    pictureId INT NOT NULL,
    model VARCHAR(255) NOT NULL,
    cost VARCHAR(255) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(markId) REFERENCES MARK(id),
    FOREIGN KEY(bodyId) REFERENCES BODY(id),
    FOREIGN KEY(pictureId) REFERENCES PICTURE(id)
);
CREATE TABLE ADMIN(
    id INT NOT NULL AUTO_INCREMENT,
    surname VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(255) NOT NULL,
    patr VARCHAR(255) NOT NULL,
    dostup INT NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE PAGE(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE CONTENT(
    id INT NOT NULL AUTO_INCREMENT,
    pageId INT NOT NULL,
    pictureId INT NOT NULL,
    content VARCHAR(8000) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(pageId) REFERENCES PAGE(id)
);
CREATE TABLE PICTURE_CONTENT(
	id INT NOT NULL,
	contentId INT NOT NULL,
	pictureId INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(contentId) REFERENCES CONTENT(id),
	FOREIGN KEY(pictureId) REFERENCES PICTURE(id)
);
CREATE TABLE ORDERS (
    id INT NOT NULL AUTO_INCREMENT,
    surname VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    patr VARCHAR(255),
    phone VARCHAR(20),
    dateTestDrive DATETIME NOT NULL,
    carId INT NOT NULL,
    status INT,
    PRIMARY KEY(id),
    FOREIGN KEY(carId) REFERENCES CAR(id)
);
CREATE TABLE AUTH (
    id INT NOT NULL AUTO_INCREMENT,
    adminId INT NOT NULL,
    cookie VARCHAR(300),
    PRIMARY KEY(id),
    FOREIGN KEY(adminId) REFERENCES ADMIN(id)
);