CREATE TABLE MARK(
    id INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE BODY(
    id INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE PICTURE(
    id INT NOT NULL,
    path VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE CAR(
    id INT NOT NULL,
    markId INT NOT NULL,
    bodyId INT NOT NULL,
    pictureId INT NOT NULL,
    model VARCHAR(255) NOT NULL,
    cost VARCHAR(255) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(markId) REFERENCES MARK(id),
    FOREIGN KEY(bodyId) REFERENCES BODY(id),
    FOREIGN KEY(pictureId) REFERENCES PICTURE(id)
);
CREATE TABLE ADMIN(
    id INT NOT NULL,
    surname VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    patr VARCHAR(255) NOT NULL,
    dostup INT NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE PAGE(
    id INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE CONTENT(
    id INT NOT NULL,
    pageId INT NOT NULL,
    pictureId INT NOT NULL,
    content VARCHAR(255) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(pageId) REFERENCES PAGE(id)
);
CREATE TABLE PICTURE_CONTENT(
	id INT NOT NULL,
	contentId INT NOT NULL,
	pictureId INT NOT NULL,
    PRIMARY KEY(id),
	FOREIGN KEY(contentId) REFERENCES CONTENT(id),
	FOREIGN KEY(pictureId) REFERENCES PICTURE(id)
);